[package]
name = "blog"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
reqwest = { version = "0.13.1", features = ["json"] }
serde = "1.0.228"
tokio = { version = "1", features = ["full"] }
